from datetime import datetime, timezone
from io import BytesIO
from typing import Iterable, Mapping, Optional

from openpyxl import Workbook
from openpyxl.styles import (
    Alignment,
    Border,
    Font,
    PatternFill,
    Side,
)
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo


EXCEL_MEDIA_TYPE = (
    "application/vnd.openxmlformats-officedocument."
    "spreadsheetml.sheet"
)


def _safe_text(value) -> str:
    if value is None:
        return ""

    return str(value)


def _safe_datetime(value) -> Optional[datetime]:
    """
    Return an Excel-compatible timezone-naive datetime.

    PostgreSQL may return timezone-aware timestamps, but Excel does not
    support tzinfo on datetime values. Convert aware values to UTC first,
    then remove the timezone metadata before writing them to the workbook.
    """

    if value is None:
        return None

    if not isinstance(value, datetime):
        return None

    if value.tzinfo is not None:
        return value.astimezone(
            timezone.utc
        ).replace(
            tzinfo=None
        )

    return value


def _get_value(record, field_name):
    if isinstance(record, Mapping):
        return record.get(field_name)

    return getattr(record, field_name, None)


def _apply_column_widths(worksheet) -> None:
    widths = {
        "A": 12,
        "B": 23,
        "C": 26,
        "D": 34,
        "E": 24,
        "F": 18,
        "G": 13,
        "H": 24,
        "I": 16,
        "J": 22,
        "K": 58,
        "L": 16,
        "M": 20,
    }

    for column_letter, width in widths.items():
        worksheet.column_dimensions[
            column_letter
        ].width = width


def _style_title_section(
    worksheet,
    company_name: str,
    generated_by: str,
    record_count: int,
) -> int:
    dark_fill = PatternFill(
        fill_type="solid",
        fgColor="0F172A",
    )

    accent_fill = PatternFill(
        fill_type="solid",
        fgColor="16A34A",
    )

    worksheet.merge_cells("A1:M1")
    worksheet["A1"] = company_name or "Mine Manager AI"

    worksheet["A1"].font = Font(
        bold=True,
        size=18,
        color="FFFFFF",
    )

    worksheet["A1"].fill = dark_fill

    worksheet["A1"].alignment = Alignment(
        vertical="center",
        horizontal="left",
    )

    worksheet.row_dimensions[1].height = 32

    worksheet.merge_cells("A2:M2")
    worksheet["A2"] = "Audit Trail Export"

    worksheet["A2"].font = Font(
        bold=True,
        size=15,
        color="FFFFFF",
    )

    worksheet["A2"].fill = accent_fill

    worksheet["A2"].alignment = Alignment(
        vertical="center",
        horizontal="left",
    )

    worksheet.row_dimensions[2].height = 27

    generated_at = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    metadata = [
        ("Generated At", generated_at),
        ("Generated By", generated_by or "Administrator"),
        ("Record Count", record_count),
    ]

    start_row = 3

    for index, (label, value) in enumerate(
        metadata,
        start=start_row,
    ):
        worksheet.cell(
            row=index,
            column=1,
            value=label,
        )

        worksheet.cell(
            row=index,
            column=2,
            value=value,
        )

        worksheet.merge_cells(
            start_row=index,
            start_column=2,
            end_row=index,
            end_column=5,
        )

        worksheet.cell(
            row=index,
            column=1,
        ).font = Font(
            bold=True,
            color="334155",
        )

        worksheet.cell(
            row=index,
            column=1,
        ).alignment = Alignment(
            vertical="center",
        )

        worksheet.cell(
            row=index,
            column=2,
        ).alignment = Alignment(
            vertical="center",
        )

    return 7


def _style_header_row(
    worksheet,
    header_row: int,
    headers,
) -> None:
    header_fill = PatternFill(
        fill_type="solid",
        fgColor="1E293B",
    )

    thin_border = Border(
        bottom=Side(
            style="thin",
            color="CBD5E1",
        )
    )

    for column_index, header in enumerate(
        headers,
        start=1,
    ):
        cell = worksheet.cell(
            row=header_row,
            column=column_index,
            value=header,
        )

        cell.font = Font(
            bold=True,
            color="FFFFFF",
        )

        cell.fill = header_fill

        cell.alignment = Alignment(
            horizontal="center",
            vertical="center",
            wrap_text=True,
        )

        cell.border = thin_border

    worksheet.row_dimensions[
        header_row
    ].height = 28


def _style_data_row(
    worksheet,
    row_index: int,
    column_count: int,
) -> None:
    alternate_fill = PatternFill(
        fill_type="solid",
        fgColor="F8FAFC",
    )

    thin_border = Border(
        bottom=Side(
            style="thin",
            color="E2E8F0",
        )
    )

    for column_index in range(
        1,
        column_count + 1,
    ):
        cell = worksheet.cell(
            row=row_index,
            column=column_index,
        )

        cell.alignment = Alignment(
            vertical="top",
            wrap_text=True,
        )

        cell.border = thin_border

        if row_index % 2 == 0:
            cell.fill = alternate_fill


def _apply_status_style(cell, status_value: str) -> None:
    normalized = str(
        status_value or ""
    ).strip().upper()

    if normalized == "SUCCESS":
        cell.fill = PatternFill(
            fill_type="solid",
            fgColor="DCFCE7",
        )

        cell.font = Font(
            bold=True,
            color="166534",
        )

    elif normalized == "FAILED":
        cell.fill = PatternFill(
            fill_type="solid",
            fgColor="FEE2E2",
        )

        cell.font = Font(
            bold=True,
            color="B91C1C",
        )

    else:
        cell.fill = PatternFill(
            fill_type="solid",
            fgColor="E2E8F0",
        )

        cell.font = Font(
            bold=True,
            color="475569",
        )

    cell.alignment = Alignment(
        horizontal="center",
        vertical="center",
    )


def generate_audit_trail_excel(
    *,
    audit_logs: Iterable,
    company_name: str,
    generated_by: str,
) -> BytesIO:
    """
    Generate a branded Audit Trail Excel workbook.

    The input may contain SQLAlchemy model objects
    or dictionary-like records.
    """

    records = list(audit_logs)

    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "Audit Trail"

    worksheet.sheet_view.showGridLines = False

    workbook.properties.title = (
        f"{company_name or 'Mine Manager AI'} "
        "Audit Trail Export"
    )

    workbook.properties.subject = (
        "Administrator and system activity audit records"
    )

    workbook.properties.creator = "Mine Manager AI"

    workbook.properties.description = (
        "Company-isolated Audit Trail export generated "
        "from Mine Manager AI."
    )

    header_row = _style_title_section(
        worksheet=worksheet,
        company_name=company_name,
        generated_by=generated_by,
        record_count=len(records),
    )

    headers = [
        "Audit ID",
        "Timestamp",
        "Actor User ID",
        "Actor Name",
        "Actor Email",
        "Action",
        "Entity Type",
        "Entity ID",
        "Entity Name",
        "Description",
        "Status",
        "IP Address",
        "Company ID",
    ]

    _style_header_row(
        worksheet=worksheet,
        header_row=header_row,
        headers=headers,
    )

    for row_index, record in enumerate(
        records,
        start=header_row + 1,
    ):
        created_at = _safe_datetime(
            _get_value(record, "created_at")
        )

        values = [
            _get_value(record, "id"),
            created_at,
            _get_value(record, "actor_user_id"),
            _safe_text(
                _get_value(record, "actor_name")
            ),
            _safe_text(
                _get_value(record, "actor_email")
            ),
            _safe_text(
                _get_value(record, "action")
            ),
            _safe_text(
                _get_value(record, "entity_type")
            ),
            _get_value(record, "entity_id"),
            _safe_text(
                _get_value(record, "entity_name")
            ),
            _safe_text(
                _get_value(record, "description")
            ),
            _safe_text(
                _get_value(record, "status")
            ),
            _safe_text(
                _get_value(record, "ip_address")
            ),
            _get_value(record, "company_id"),
        ]

        for column_index, value in enumerate(
            values,
            start=1,
        ):
            worksheet.cell(
                row=row_index,
                column=column_index,
                value=value,
            )

        _style_data_row(
            worksheet=worksheet,
            row_index=row_index,
            column_count=len(headers),
        )

        timestamp_cell = worksheet.cell(
            row=row_index,
            column=2,
        )

        if created_at is not None:
            timestamp_cell.number_format = (
                "yyyy-mm-dd hh:mm:ss"
            )

        status_cell = worksheet.cell(
            row=row_index,
            column=11,
        )

        _apply_status_style(
            status_cell,
            _get_value(record, "status"),
        )

    last_row = header_row + len(records)

    if records:
        table_reference = (
            f"A{header_row}:"
            f"{get_column_letter(len(headers))}"
            f"{last_row}"
        )

        table = Table(
            displayName="AuditTrailRecords",
            ref=table_reference,
        )

        table_style = TableStyleInfo(
            name="TableStyleMedium2",
            showFirstColumn=False,
            showLastColumn=False,
            showRowStripes=False,
            showColumnStripes=False,
        )

        table.tableStyleInfo = table_style
        worksheet.add_table(table)

    worksheet.freeze_panes = (
        f"A{header_row + 1}"
    )

    worksheet.auto_filter.ref = (
        f"A{header_row}:"
        f"{get_column_letter(len(headers))}"
        f"{max(last_row, header_row)}"
    )

    _apply_column_widths(worksheet)

    worksheet.sheet_properties.pageSetUpPr.fitToPage = True
    worksheet.page_setup.orientation = "landscape"
    worksheet.page_setup.fitToWidth = 1
    worksheet.page_setup.fitToHeight = 0
    worksheet.print_title_rows = (
        f"{header_row}:{header_row}"
    )

    worksheet.page_margins.left = 0.25
    worksheet.page_margins.right = 0.25
    worksheet.page_margins.top = 0.5
    worksheet.page_margins.bottom = 0.5

    buffer = BytesIO()
    workbook.save(buffer)
    buffer.seek(0)

    return buffer