from __future__ import annotations

import re
from datetime import date, datetime
from functools import lru_cache
from typing import Literal
from urllib.parse import quote


ReportLanguage = Literal["en", "mn"]
DateFormatPurpose = Literal[
    "full_report_date",
    "reporting_period_date",
    "generated_timestamp",
    "short_chart_date",
]


_MONGOLIAN_LANGUAGE_VALUES = {
    "mn",
    "mongolian",
    "монгол",
}

_COMMON_LABELS = {
    "en": {
        "stable": "Stable",
        "watch": "Watch",
        "critical": "Critical",
        "improving": "Improving",
        "declining": "Declining",
        "no_data": "No data",
        "on_track": "On Track",
        "above_target": "Above Target",
        "below_target": "Below Target",
        "medium": "Medium",
        "high": "High",
        "low": "Low",
        "open": "Open",
        "unassigned": "Unassigned",
        "not_set": "Not set",
        "reporting_period": "Reporting period",
        "generated": "Generated",
        "page": "Page",
        "generated_by_mine_manager_ai": "Generated by Mine Manager AI",
        "daily_report": "Daily Executive Report",
        "mine_health": "Mine Health",
        "overall_operating_condition": "Overall operating condition",
        "today_at_a_glance": "Today at a Glance",
        "management_attention": "Management Attention",
        "executive_brief": "Executive Brief",
        "todays_actions": "Today's Actions",
        "operation_status": "Operation Status",
        "production": "Production",
        "plant": "Plant",
        "safety": "Safety",
        "fleet": "Fleet",
        "impact": "Impact",
        "action": "Action",
        "availability": "Availability",
        "utilization": "Utilization",
        "throughput": "Throughput",
        "recovery": "Recovery",
        "safety_exposure": "Safety exposure",
        "fleet_performance": "Fleet performance",
        "plant_performance": "Plant performance",
        "cathode_production": "Cathode Production",
        "ore_production": "Ore Production",
        "weekly_report": "Weekly Operations Report",
        "weekly_mine_health": "Weekly Mine Health",
        "overall_weekly_operating_condition": "Overall weekly operating condition",
        "weekly_performance_at_a_glance": "Weekly Performance at a Glance",
        "weekly_trends": "Weekly Trends",
        "trend": "Trend",
        "plant_throughput": "Plant Throughput",
        "plant_recovery": "Plant Recovery",
        "next_week_actions": "Next-Week Actions",
        "next_week_outlook": "Next-Week Outlook",
        "weekly_kpi_detail": "Weekly KPI Detail",
        "weekly_operating_status": "Weekly Operating Status",
        "performance": "Performance",
        "status": "Status",
        "area": "Area",
        "outlook_focus": "Outlook / Focus",
        "target": "Target",
        "result": "Result",
        "variance": "Variance",
        "actual": "Actual",
        "events": "Events",
        "score": "Score",
        "monthly_report": "Monthly KPI Pack",
        "monthly_mine_health": "Monthly Mine Health",
        "overall_monthly_operating_condition": "Overall monthly operating condition",
        "monthly_performance_at_a_glance": "Monthly Performance at a Glance",
        "monthly_trends": "Monthly Performance Trends",
        "daily_performance_across_reporting_period": "Daily Performance Across the Reporting Period",
        "strategic_actions": "Strategic Actions",
        "next_month_outlook": "Next-Month Outlook",
        "monthly_kpi_detail": "Monthly KPI Detail",
        "monthly_operating_status": "Monthly Operating Status",
        "safety_score": "Safety Score",
        "excel_sheet_executive_summary": "Executive Summary",
        "excel_sheet_cathode_production": "Cathode Production",
        "excel_sheet_production": "Production",
        "excel_sheet_fleet": "Fleet",
        "excel_sheet_plant": "Plant",
        "excel_sheet_safety": "Safety",
        "excel_sheet_kpi_definitions": "KPI Definitions",
        "executive_operations_summary": "Executive Operations Summary",
        "executive_operations_export": "Executive Operations Export",
        "company": "Company",
        "mine": "Mine",
        "operation": "Operation",
        "operation_profile": "Operation Profile",
        "sxew_copper": "SX-EW Copper",
        "standard_mine": "Standard Mine",
        "latest_report_date": "Latest Report Date",
        "latest_kpi_position": "Latest KPI Position",
        "current_value": "Current Value",
        "excel_below_target": "Below target",
        "excel_safety_score_summary": "Safety score",
        "on_or_above_target": "On or above target",
        "data_coverage": "Data Coverage",
        "cathode_production_achievement": "Cathode production achievement",
        "cathode_production_achievement_definition_name": "Cathode Production Achievement",
        "plant_throughput_achievement": "Plant throughput achievement",
        "ore_plan_achievement": "Ore plan achievement",
        "waste_plan_achievement": "Waste plan achievement",
        "fleet_availability": "Fleet availability",
        "fleet_utilization": "Fleet utilization",
        "cathode_production_records": "Cathode production records",
        "production_records": "Production records",
        "fleet_records": "Fleet records",
        "plant_records": "Plant records",
        "safety_records": "Safety records",
        "cathode_production_performance": "Cathode Production Performance",
        "production_performance": "Production Performance",
        "daily_cathode_production_performance": "Daily cathode production performance",
        "daily_mining_production_performance": "Daily mining production performance",
        "report_date": "Report Date",
        "production_plan": "Production Plan",
        "production_actual": "Production Actual",
        "ore_plan": "Ore Plan",
        "ore_actual": "Ore Actual",
        "ore_variance": "Ore Variance",
        "ore_achievement": "Ore Achievement",
        "waste_plan": "Waste Plan",
        "waste_actual": "Waste Actual",
        "waste_variance": "Waste Variance",
        "achievement": "Achievement",
        "created_at": "Created At",
        "fleet_performance_title": "Fleet Performance",
        "fleet_availability_and_utilization": "Fleet availability and utilization",
        "plant_performance_title": "Plant Performance",
        "plant_throughput_and_recovery": "Plant throughput and recovery",
        "throughput_plan": "Throughput Plan",
        "throughput_actual": "Throughput Actual",
        "safety_performance_title": "Safety Performance",
        "safety_performance_and_critical_risk_indicators": "Safety performance and critical risk indicators",
        "incidents": "Incidents",
        "near_misses": "Near Misses",
        "critical_risks": "Critical Risks",
        "definitions_used_in_workbook": "Definitions used in this workbook",
        "category": "Category",
        "definition": "Definition",
        "calculation": "Calculation",
        "interpretation": "Interpretation",
        "count": "Count",
        "cathode_production_achievement_definition": "Actual cathode production compared with planned cathode production.",
        "cathode_production_achievement_calculation": "Production Actual ÷ Production Plan",
        "plan_achieved_interpretation": "100% or above indicates plan was achieved.",
        "throughput_achievement": "Throughput Achievement",
        "throughput_achievement_definition": "Actual processing throughput compared with plan.",
        "throughput_achievement_calculation": "Throughput Actual ÷ Throughput Plan",
        "recovery_definition": "Percentage of valuable material recovered through processing.",
        "recovery_calculation": "Recovered Value ÷ Feed Value",
        "higher_is_better": "Higher is generally better.",
        "incidents_definition": "Recorded safety incidents for the reporting date.",
        "zero_is_preferred": "Zero is preferred.",
        "near_misses_definition": "Reported events that could have caused harm or loss.",
        "requires_review_follow_up": "Requires review and follow-up.",
        "critical_risks_definition": "Open or observed critical risk exposures.",
        "zero_unresolved_critical_exposures": "Zero unresolved critical exposures is preferred.",
        "safety_score_definition": "Composite safety performance indicator.",
        "safety_score_calculation": "Configured safety scoring methodology",
        "ore_plan_achievement_definition": "Actual ore movement compared with planned ore movement.",
        "ore_plan_achievement_calculation": "Ore Actual ÷ Ore Plan",
        "waste_plan_achievement_definition": "Actual waste movement compared with planned waste movement.",
        "waste_plan_achievement_calculation": "Waste Actual ÷ Waste Plan",
        "availability_definition": "Percentage of scheduled time that equipment is available.",
        "availability_calculation": "Available Time ÷ Scheduled Time",
        "utilization_definition": "Percentage of available time that equipment is operating.",
        "utilization_calculation": "Operating Time ÷ Available Time",
        "executive_operations_board_pack": "Executive Operations Board Pack",
        "executive_operations_board_pack_cover": "Executive Operations\nBoard Pack",
        "executive_kpi_summary": "Executive KPI Summary",
        "cathode_production_trend": "Cathode Production Trend",
        "production_trend": "Production Trend",
        "plant_and_safety_overview": "Plant and Safety Overview",
        "fleet_plant_and_safety_overview": "Fleet, Plant and Safety Overview",
        "key_operational_risks": "Key Operational Risks",
        "management_action_register": "Management Action Register",
        "executive_recommendations": "Executive Recommendations",
        "current_position_sxew": "Current operational position across cathode production, plant, and safety",
        "current_position_standard": "Current operational position across production, fleet, plant, and safety",
        "cathode_actual_vs_plan": "Actual cathode production compared with plan",
        "cathode_plan_vs_actual_performance": "Cathode production plan versus actual performance",
        "ore_plan_vs_actual_performance": "Ore production plan versus actual performance",
        "ore_actual_vs_plan": "Actual ore movement compared with plan",
        "throughput_actual_vs_plan": "Actual throughput compared with plan",
        "latest_composite_safety_score": "Latest composite safety score",
        "powerpoint_safety_score": "Safety score",
        "safety_incidents": "Safety incidents",
        "powerpoint_near_misses": "Near misses",
        "powerpoint_critical_risks": "Critical risks",
        "latest_reporting_date": "Latest reporting date",
        "latest_available_fleet_record": "Latest available fleet record",
        "no_incidents": "No incidents",
        "review_required": "Review required",
        "on_or_above_target_status": "On / above target",
        "below_target_status": "Below target",
        "cathode_plan": "Cathode Plan",
        "cathode_actual": "Cathode Actual",
        "recent_reporting_periods": "Recent reporting periods",
        "latest_position": "Latest position",
        "cathode_plan_label": "Cathode plan",
        "cathode_actual_label": "Cathode actual",
        "recent_processing_and_safety": "Recent processing and safety performance",
        "recent_supporting_value_streams": "Recent operational performance across supporting value streams",
        "latest_safety_position": "Latest safety position",
        "automated_risk_observations": "Automated observations from the latest available operational records",
        "cathode_materially_below_plan": "Cathode production materially below plan",
        "cathode_below_plan": "Cathode production below plan",
        "ore_materially_below_plan": "Ore production materially below plan",
        "ore_below_plan": "Ore production below plan",
        "fleet_availability_constraint": "Fleet availability constraint",
        "fleet_availability_below_target": "Fleet availability below target",
        "fleet_utilization_constraint": "Fleet utilization constraint",
        "fleet_utilization_below_target": "Fleet utilization below target",
        "plant_throughput_materially_below_plan": "Plant throughput materially below plan",
        "plant_throughput_below_plan": "Plant throughput below plan",
        "safety_incident_recorded": "Safety incident recorded",
        "open_critical_safety_risks": "Open critical safety risks",
        "no_material_threshold_exception": "No material threshold exception detected",
        "latest_achievement_sentence": "Latest achievement is {value}%.",
        "latest_availability_sentence": "Latest availability is {value}%.",
        "latest_utilization_sentence": "Latest utilization is {value}%.",
        "incident_latest_record_sentence": "{count} incident(s) in the latest record.",
        "critical_exposure_review_sentence": "{count} critical risk exposure(s) require review.",
        "screening_threshold_sentence": "Latest records are within the basic automated screening thresholds.",
        "priority_actions_subtitle": "Priority actions requiring executive attention and ownership",
        "no_executive_actions": "No executive actions are currently available.",
        "priority": "Priority",
        "owner": "Owner",
        "timing": "Timing",
        "untitled_action": "Untitled action",
        "in_progress": "In_Progress",
        "not_started": "Not Started",
        "completed": "Completed",
        "overdue": "Overdue",
        "recommendations_subtitle": "Recommended management focus for the next operating cycle",
        "recommended_next_actions": "Recommended next actions",
        "executive_focus": "Executive focus",
        "executive_focus_statement": "Safety first.\nProtect the plan.\nClose the actions.",
        "board_pack_disclaimer": "This board pack summarizes current operational records and supports—not replaces—management judgment.",
        "recommend_safety_controls": "Confirm immediate controls, ownership, and close-out timing for all current safety incidents and critical risk exposures.",
        "recommend_cathode_recovery_plan": "Review the cathode production constraint and agree a recoverable production plan for the next operating cycle.",
        "recommend_ore_recovery_plan": "Review the primary production constraint and agree a recoverable plan for ore movement before the next shift cycle.",
        "recommend_availability_actions": "Prioritize the equipment availability loss tree and confirm maintenance recovery actions for the highest-impact assets.",
        "recommend_utilization_actions": "Review dispatch, delay, and operating-time losses to convert available fleet capacity into productive utilization.",
        "recommend_sxew_throughput": "Validate the plant throughput constraint and align processing priorities with the next achievable cathode production target.",
        "recommend_standard_throughput": "Validate the plant throughput constraint and align mine-to-mill priorities with the next achievable production target.",
        "recommend_accountable_owner": "Keep one accountable owner and one completion date for each executive action.",
        "recommend_daily_exceptions": "Review exceptions against plan daily and escalate only the highest-value operational decisions.",
        "recommend_data_quality": "Confirm data quality before using KPI movements for management decisions.",
        "generated_metadata": "Generated",
        "timezone": "Timezone",
        "no_trend_data_available": "No trend data available",
    },
    "mn": {
        "stable": "Тогтвортой",
        "watch": "Анхаарах",
        "critical": "Ноцтой",
        "improving": "Сайжирч байна",
        "declining": "Буурч байна",
        "no_data": "Өгөгдөлгүй",
        "on_track": "Төлөвлөгөөний дагуу",
        "above_target": "Зорилтоос дээгүүр",
        "below_target": "Зорилтоос доогуур",
        "medium": "Дунд",
        "high": "Өндөр",
        "low": "Бага",
        "open": "Нээлттэй",
        "unassigned": "Хариуцагчгүй",
        "not_set": "Тодорхойлоогүй",
        "reporting_period": "Тайлант хугацаа",
        "generated": "Үүсгэсэн",
        "page": "Хуудас",
        "generated_by_mine_manager_ai": "Mine Manager AI-аар үүсгэв",
        "daily_report": "Өдрийн Удирдлагын Тайлан",
        "mine_health": "Уурхайн Үйл Ажиллагааны Үнэлгээ",
        "overall_operating_condition": "Үйл ажиллагааны ерөнхий нөхцөл",
        "today_at_a_glance": "Өнөөдрийн Товч Үзүүлэлт",
        "management_attention": "Удирдлагын Анхаарах Асуудал",
        "executive_brief": "Удирдлагын Товч Дүгнэлт",
        "todays_actions": "Өнөөдрийн Арга Хэмжээ",
        "operation_status": "Үйл Ажиллагааны Төлөв",
        "production": "Үйлдвэрлэл",
        "plant": "Боловсруулах Үйлдвэр",
        "safety": "Аюулгүй Ажиллагаа",
        "fleet": "Техникийн Парк",
        "impact": "Нөлөөлөл",
        "action": "Арга Хэмжээ",
        "availability": "Бэлэн Байдал",
        "utilization": "Ашиглалт",
        "throughput": "Нэвтрүүлэх чадвар",
        "recovery": "Металл авалт",
        "safety_exposure": "Аюулгүй ажиллагааны эрсдэл",
        "fleet_performance": "Техникийн паркийн гүйцэтгэл",
        "plant_performance": "Боловсруулах үйлдвэрийн гүйцэтгэл",
        "cathode_production": "Катодын үйлдвэрлэл",
        "ore_production": "Хүдрийн үйлдвэрлэл",
        "weekly_report": "Долоо Хоногийн Үйл Ажиллагааны Тайлан",
        "weekly_mine_health": "Долоо Хоногийн Уурхайн Үйл Ажиллагааны Үнэлгээ",
        "overall_weekly_operating_condition": "Долоо хоногийн үйл ажиллагааны ерөнхий нөхцөл",
        "weekly_performance_at_a_glance": "Долоо Хоногийн Товч Гүйцэтгэл",
        "weekly_trends": "Долоо Хоногийн Хандлага",
        "trend": "Хандлага",
        "plant_throughput": "Боловсруулах Үйлдвэрийн Нэвтрүүлэх Чадвар",
        "plant_recovery": "Металл Авалт",
        "next_week_actions": "Ирэх Долоо Хоногийн Арга Хэмжээ",
        "next_week_outlook": "Ирэх Долоо Хоногийн Төлөв",
        "weekly_kpi_detail": "Долоо Хоногийн KPI Дэлгэрэнгүй",
        "weekly_operating_status": "Долоо Хоногийн Үйл Ажиллагааны Төлөв",
        "performance": "Гүйцэтгэл",
        "status": "Төлөв",
        "area": "Чиглэл",
        "outlook_focus": "Төлөв / Гол Анхаарах Чиглэл",
        "target": "Зорилтот Үзүүлэлт",
        "result": "Үр Дүн",
        "variance": "Зөрүү",
        "actual": "Бодит Гүйцэтгэл",
        "events": "Үйл Явдал",
        "score": "Үнэлгээ",
        "monthly_report": "Сарын KPI Тайлан",
        "monthly_mine_health": "Уурхайн Үйл Ажиллагааны Үнэлгээ",
        "overall_monthly_operating_condition": "Сарын үйл ажиллагааны ерөнхий нөхцөл",
        "monthly_performance_at_a_glance": "Сарын Товч Гүйцэтгэл",
        "monthly_trends": "Сарын Гүйцэтгэлийн Хандлага",
        "daily_performance_across_reporting_period": "Тайлант хугацааны өдрийн гүйцэтгэл",
        "strategic_actions": "Стратегийн Арга Хэмжээ",
        "next_month_outlook": "Ирэх Сарын Төлөв",
        "monthly_kpi_detail": "KPI Дэлгэрэнгүй",
        "monthly_operating_status": "Үйл Ажиллагааны Төлөв",
        "safety_score": "Аюулгүй Ажиллагааны Үнэлгээ",
        "excel_sheet_executive_summary": "Удирдлагын Товч",
        "excel_sheet_cathode_production": "Катодын Үйлдвэрлэл",
        "excel_sheet_production": "Үйлдвэрлэл",
        "excel_sheet_fleet": "Техникийн Парк",
        "excel_sheet_plant": "Боловсруулах Үйлдвэр",
        "excel_sheet_safety": "Аюулгүй Ажиллагаа",
        "excel_sheet_kpi_definitions": "KPI Тайлбар",
        "executive_operations_summary": "Удирдлагын Үйл Ажиллагааны Товч",
        "executive_operations_export": "Удирдлагын Тайлангийн Экспорт",
        "company": "Компани",
        "mine": "Уурхай",
        "operation": "Үйл ажиллагаа",
        "operation_profile": "Үйл ажиллагааны төрөл",
        "sxew_copper": "SX-EW зэс",
        "standard_mine": "Ердийн уурхай",
        "latest_report_date": "Тайлангийн Огноо",
        "latest_kpi_position": "Сүүлийн KPI Үзүүлэлт",
        "current_value": "Бодит Гүйцэтгэл",
        "excel_below_target": "Зорилтоос доогуур",
        "excel_safety_score_summary": "Аюулгүй Ажиллагааны Үнэлгээ",
        "on_or_above_target": "Зорилтот түвшинд эсвэл түүнээс дээш",
        "data_coverage": "Өгөгдлийн Хамрах Хүрээ",
        "cathode_production_achievement": "Катодын үйлдвэрлэлийн гүйцэтгэл",
        "cathode_production_achievement_definition_name": "Катодын Үйлдвэрлэлийн Гүйцэтгэл",
        "plant_throughput_achievement": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадварын гүйцэтгэл",
        "ore_plan_achievement": "Хүдрийн төлөвлөгөөний гүйцэтгэл",
        "waste_plan_achievement": "Хөрс хуулалтын төлөвлөгөөний гүйцэтгэл",
        "fleet_availability": "Техникийн паркийн бэлэн байдал",
        "fleet_utilization": "Техникийн паркийн ашиглалт",
        "cathode_production_records": "Катодын үйлдвэрлэлийн бүртгэл",
        "production_records": "Үйлдвэрлэлийн бүртгэл",
        "fleet_records": "Техникийн паркийн бүртгэл",
        "plant_records": "Боловсруулах үйлдвэрийн бүртгэл",
        "safety_records": "Аюулгүй ажиллагааны бүртгэл",
        "cathode_production_performance": "Катодын Үйлдвэрлэлийн Гүйцэтгэл",
        "production_performance": "Үйлдвэрлэлийн Гүйцэтгэл",
        "daily_cathode_production_performance": "Өдрийн катодын үйлдвэрлэлийн гүйцэтгэл",
        "daily_mining_production_performance": "Өдрийн уурхайн үйлдвэрлэлийн гүйцэтгэл",
        "report_date": "Огноо",
        "production_plan": "Үйлдвэрлэлийн Төлөвлөгөө",
        "production_actual": "Үйлдвэрлэлийн Бодит",
        "ore_plan": "Хүдрийн Төлөвлөгөө",
        "ore_actual": "Хүдрийн Бодит",
        "ore_variance": "Хүдрийн Зөрүү",
        "ore_achievement": "Хүдрийн Гүйцэтгэл",
        "waste_plan": "Хөрс Хуулалтын Төлөвлөгөө",
        "waste_actual": "Хөрс Хуулалтын Бодит",
        "waste_variance": "Хөрс Хуулалтын Зөрүү",
        "achievement": "Гүйцэтгэл",
        "created_at": "Үүсгэсэн",
        "fleet_performance_title": "Техникийн Паркийн Гүйцэтгэл",
        "fleet_availability_and_utilization": "Техникийн паркийн бэлэн байдал ба ашиглалт",
        "plant_performance_title": "Боловсруулах Үйлдвэрийн Гүйцэтгэл",
        "plant_throughput_and_recovery": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадвар ба металл авалт",
        "throughput_plan": "Нэвтрүүлэх Чадварын Төлөвлөгөө",
        "throughput_actual": "Нэвтрүүлэх Чадварын Бодит",
        "safety_performance_title": "Аюулгүй Ажиллагааны Гүйцэтгэл",
        "safety_performance_and_critical_risk_indicators": "Аюулгүй ажиллагааны гүйцэтгэл ба ноцтой эрсдэлийн үзүүлэлт",
        "incidents": "Осол",
        "near_misses": "Осолд Дөхсөн Тохиолдол",
        "critical_risks": "Ноцтой Эрсдэл",
        "definitions_used_in_workbook": "Энэ ажлын номд ашигласан тодорхойлолт",
        "category": "Ангилал",
        "definition": "Тодорхойлолт",
        "calculation": "Тооцоолол",
        "interpretation": "Тайлбар",
        "count": "Тоо",
        "cathode_production_achievement_definition": "Катодын бодит үйлдвэрлэлийг төлөвлөсөн катодын үйлдвэрлэлтэй харьцуулна.",
        "cathode_production_achievement_calculation": "Үйлдвэрлэлийн Бодит ÷ Үйлдвэрлэлийн Төлөвлөгөө",
        "plan_achieved_interpretation": "100% болон түүнээс дээш бол төлөвлөгөө биелснийг илтгэнэ.",
        "throughput_achievement": "Нэвтрүүлэх Чадварын Гүйцэтгэл",
        "throughput_achievement_definition": "Бодит боловсруулах нэвтрүүлэх чадварыг төлөвлөгөөтэй харьцуулна.",
        "throughput_achievement_calculation": "Нэвтрүүлэх Чадварын Бодит ÷ Нэвтрүүлэх Чадварын Төлөвлөгөө",
        "recovery_definition": "Боловсруулалтаар гарган авсан үнэт материалын хувь.",
        "recovery_calculation": "Гарган авсан үнэт материал ÷ Тэжээл дэх үнэт материал",
        "higher_is_better": "Өндөр байх нь ерөнхийдөө сайн.",
        "incidents_definition": "Тайлант өдөр бүртгэгдсэн аюулгүй ажиллагааны ослын тоо.",
        "zero_is_preferred": "Тэг байхыг зорино.",
        "near_misses_definition": "Хохирол, гэмтэл учруулж болзошгүй байсан бүртгэгдсэн тохиолдол.",
        "requires_review_follow_up": "Шалгаж, дараагийн арга хэмжээг хэрэгжүүлэх шаардлагатай.",
        "critical_risks_definition": "Нээлттэй эсвэл ажиглагдсан ноцтой эрсдэлийн өртөлт.",
        "zero_unresolved_critical_exposures": "Шийдвэрлээгүй ноцтой эрсдэлийн өртөлтгүй байхыг зорино.",
        "safety_score_definition": "Аюулгүй ажиллагааны гүйцэтгэлийн нийлмэл үзүүлэлт.",
        "safety_score_calculation": "Тохируулсан аюулгүй ажиллагааны үнэлгээний аргачлал",
        "ore_plan_achievement_definition": "Хүдрийн бодит хөдөлгөөнийг төлөвлөсөн хүдрийн хөдөлгөөнтэй харьцуулна.",
        "ore_plan_achievement_calculation": "Хүдрийн Бодит ÷ Хүдрийн Төлөвлөгөө",
        "waste_plan_achievement_definition": "Хөрс хуулалтын бодит хэмжээг төлөвлөсөн хэмжээтэй харьцуулна.",
        "waste_plan_achievement_calculation": "Хөрс Хуулалтын Бодит ÷ Хөрс Хуулалтын Төлөвлөгөө",
        "availability_definition": "Тоног төхөөрөмж төлөвлөсөн хугацаанд бэлэн байсан хувь.",
        "availability_calculation": "Бэлэн Хугацаа ÷ Төлөвлөсөн Хугацаа",
        "utilization_definition": "Тоног төхөөрөмж бэлэн хугацаандаа ажилласан хувь.",
        "utilization_calculation": "Ажилласан Хугацаа ÷ Бэлэн Хугацаа",
        "executive_operations_board_pack": "Удирдлагын Үйл Ажиллагааны Танилцуулга",
        "executive_operations_board_pack_cover": "Удирдлагын Үйл Ажиллагааны Танилцуулга",
        "executive_kpi_summary": "Удирдлагын KPI Товч",
        "cathode_production_trend": "Катодын Үйлдвэрлэлийн Хандлага",
        "production_trend": "Үйлдвэрлэлийн Хандлага",
        "plant_and_safety_overview": "Боловсруулах Үйлдвэр ба Аюулгүй Ажиллагаа",
        "fleet_plant_and_safety_overview": "Техникийн Парк, Боловсруулах Үйлдвэр ба Аюулгүй Ажиллагаа",
        "key_operational_risks": "Үйл Ажиллагааны Гол Эрсдэлүүд",
        "management_action_register": "Удирдлагын Арга Хэмжээний Бүртгэл",
        "executive_recommendations": "Удирдлагын Зөвлөмж",
        "current_position_sxew": "Катодын үйлдвэрлэл, боловсруулах үйлдвэр болон аюулгүй ажиллагааны одоогийн төлөв",
        "current_position_standard": "Үйлдвэрлэл, техникийн парк, боловсруулах үйлдвэр болон аюулгүй ажиллагааны одоогийн төлөв",
        "cathode_actual_vs_plan": "Катодын бодит үйлдвэрлэлийг төлөвлөгөөтэй харьцуулсан үзүүлэлт",
        "cathode_plan_vs_actual_performance": "Катодын үйлдвэрлэлийн төлөвлөгөө ба бодит гүйцэтгэл",
        "ore_plan_vs_actual_performance": "Хүдрийн үйлдвэрлэлийн төлөвлөгөө ба бодит гүйцэтгэл",
        "ore_actual_vs_plan": "Хүдрийн бодит хөдөлгөөнийг төлөвлөгөөтэй харьцуулсан үзүүлэлт",
        "throughput_actual_vs_plan": "Бодит нэвтрүүлэх чадварыг төлөвлөгөөтэй харьцуулсан үзүүлэлт",
        "latest_composite_safety_score": "Аюулгүй ажиллагааны нийлмэл үнэлгээний сүүлийн утга",
        "powerpoint_safety_score": "Аюулгүй Ажиллагааны Үнэлгээ",
        "safety_incidents": "Осол",
        "powerpoint_near_misses": "Осолд Дөхсөн Тохиолдол",
        "powerpoint_critical_risks": "Ноцтой Эрсдэл",
        "latest_reporting_date": "Сүүлийн тайлангийн огноо",
        "latest_available_fleet_record": "Техникийн паркийн сүүлийн бүртгэл",
        "no_incidents": "Осолгүй",
        "review_required": "Хянан үзэх шаардлагатай",
        "on_or_above_target_status": "Зорилтот түвшинд эсвэл түүнээс дээш",
        "below_target_status": "Зорилтоос доогуур",
        "cathode_plan": "Катодын Төлөвлөгөө",
        "cathode_actual": "Катодын Бодит Гүйцэтгэл",
        "recent_reporting_periods": "Сүүлийн тайлант хугацаа",
        "latest_position": "Сүүлийн Үзүүлэлт",
        "cathode_plan_label": "Катодын төлөвлөгөө",
        "cathode_actual_label": "Катодын бодит гүйцэтгэл",
        "recent_processing_and_safety": "Боловсруулалт болон аюулгүй ажиллагааны сүүлийн гүйцэтгэл",
        "recent_supporting_value_streams": "Үйл ажиллагааг дэмжих чиглэлүүдийн сүүлийн гүйцэтгэл",
        "latest_safety_position": "Аюулгүй Ажиллагааны Сүүлийн Үзүүлэлт",
        "automated_risk_observations": "Сүүлийн үйл ажиллагааны бүртгэлд үндэслэсэн автомат ажиглалт",
        "cathode_materially_below_plan": "Катодын үйлдвэрлэл төлөвлөгөөнөөс мэдэгдэхүйц доогуур",
        "cathode_below_plan": "Катодын үйлдвэрлэл төлөвлөгөөнөөс доогуур",
        "ore_materially_below_plan": "Хүдрийн үйлдвэрлэл төлөвлөгөөнөөс мэдэгдэхүйц доогуур",
        "ore_below_plan": "Хүдрийн үйлдвэрлэл төлөвлөгөөнөөс доогуур",
        "fleet_availability_constraint": "Техникийн паркийн бэлэн байдлын хязгаарлалт",
        "fleet_availability_below_target": "Техникийн паркийн бэлэн байдал зорилтоос доогуур",
        "fleet_utilization_constraint": "Техникийн паркийн ашиглалтын хязгаарлалт",
        "fleet_utilization_below_target": "Техникийн паркийн ашиглалт зорилтоос доогуур",
        "plant_throughput_materially_below_plan": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадвар төлөвлөгөөнөөс мэдэгдэхүйц доогуур",
        "plant_throughput_below_plan": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадвар төлөвлөгөөнөөс доогуур",
        "safety_incident_recorded": "Аюулгүй ажиллагааны осол бүртгэгдсэн",
        "open_critical_safety_risks": "Шийдвэрлээгүй ноцтой аюулгүй ажиллагааны эрсдэл",
        "no_material_threshold_exception": "Босго үзүүлэлтээс ноцтой зөрүү илрээгүй",
        "latest_achievement_sentence": "Сүүлийн гүйцэтгэл {value}% байна.",
        "latest_availability_sentence": "Сүүлийн бэлэн байдал {value}% байна.",
        "latest_utilization_sentence": "Сүүлийн ашиглалт {value}% байна.",
        "incident_latest_record_sentence": "Сүүлийн бүртгэлд {count} осол бүртгэгдсэн.",
        "critical_exposure_review_sentence": "{count} ноцтой эрсдэлийн өртөлтийг хянан үзэх шаардлагатай.",
        "screening_threshold_sentence": "Сүүлийн бүртгэлүүд автомат хяналтын үндсэн босго үзүүлэлтийн хүрээнд байна.",
        "priority_actions_subtitle": "Удирдлагын анхаарал болон хариуцагч шаардсан эрэмбэлэгдсэн арга хэмжээ",
        "no_executive_actions": "Удирдлагын арга хэмжээ одоогоор бүртгэгдээгүй байна.",
        "priority": "Эрэмбэ",
        "owner": "Хариуцагч",
        "timing": "Хугацаа",
        "untitled_action": "Нэргүй арга хэмжээ",
        "in_progress": "Хэрэгжиж Байна",
        "not_started": "Эхлээгүй",
        "completed": "Дууссан",
        "overdue": "Хугацаа Хэтэрсэн",
        "recommendations_subtitle": "Дараагийн үйл ажиллагааны мөчлөгт удирдлагаас анхаарах чиглэл",
        "recommended_next_actions": "Зөвлөсөн Дараагийн Арга Хэмжээ",
        "executive_focus": "Удирдлагын Гол Анхаарах Чиглэл",
        "executive_focus_statement": "Аюулгүй ажиллагааг нэн тэргүүнд.\nТөлөвлөгөөг хамгаал.\nАрга хэмжээг дуусга.",
        "board_pack_disclaimer": "Энэхүү танилцуулга нь үйл ажиллагааны одоогийн бүртгэлийг нэгтгэн харуулах бөгөөд удирдлагын шийдвэрийг орлохгүй.",
        "recommend_safety_controls": "Одоогийн аюулгүй ажиллагааны осол болон ноцтой эрсдэлийн өртөлт бүрийн хяналт, хариуцагч, хаах хугацааг нэн даруй баталгаажуул.",
        "recommend_cathode_recovery_plan": "Катодын үйлдвэрлэлийн хязгаарлалтыг хянан үзэж, дараагийн үйл ажиллагааны мөчлөгт нөхөн гүйцэтгэх үйлдвэрлэлийн төлөвлөгөөг тохиролц.",
        "recommend_ore_recovery_plan": "Үйлдвэрлэлийн үндсэн хязгаарлалтыг хянан үзэж, дараагийн ээлжийн мөчлөгөөс өмнө хүдрийн хөдөлгөөний нөхөн гүйцэтгэх төлөвлөгөөг тохиролц.",
        "recommend_availability_actions": "Тоног төхөөрөмжийн бэлэн байдлын алдагдлын шалтгааныг эрэмбэлж, хамгийн өндөр нөлөөтэй тоног төхөөрөмжийн засварын арга хэмжээг баталгаажуул.",
        "recommend_utilization_actions": "Бэлэн хүчин чадлыг үр ашигтай ашиглахын тулд диспетчерчлэл, саатал болон ажилласан хугацааны алдагдлыг хянан үз.",
        "recommend_sxew_throughput": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадварын хязгаарлалтыг баталгаажуулж, боловсруулалтын тэргүүлэх чиглэлийг дараагийн хүрч болох катодын үйлдвэрлэлийн зорилттой уялдуул.",
        "recommend_standard_throughput": "Боловсруулах үйлдвэрийн нэвтрүүлэх чадварын хязгаарлалтыг баталгаажуулж, уурхайгаас үйлдвэр хүртэлх тэргүүлэх чиглэлийг дараагийн хүрч болох үйлдвэрлэлийн зорилттой уялдуул.",
        "recommend_accountable_owner": "Удирдлагын арга хэмжээ бүрт нэг хариуцагч, нэг дуусгах хугацааг тогтоо.",
        "recommend_daily_exceptions": "Төлөвлөгөөний зөрүүг өдөр бүр хянаж, зөвхөн хамгийн өндөр өгөөжтэй үйл ажиллагааны шийдвэрийг шатлан мэдээл.",
        "recommend_data_quality": "KPI-ийн өөрчлөлтийг удирдлагын шийдвэрт ашиглахаас өмнө өгөгдлийн чанарыг баталгаажуул.",
        "generated_metadata": "Үүсгэсэн",
        "timezone": "Цагийн бүс",
        "no_trend_data_available": "Хандлагын өгөгдөл байхгүй",
    },
}

_REPORT_DEFINITIONS = {
    "daily_pdf": {
        "extension": "pdf",
        "en_stem": "Daily_Executive_Report",
        "mn_stem": "Өдрийн_Удирдлагын_Тайлан",
        "en_name": "Daily Executive Report",
        "mn_name": "Өдрийн удирдлагын тайлан",
    },
    "weekly_pdf": {
        "extension": "pdf",
        "en_stem": "Weekly_Operations_Report",
        "mn_stem": "Долоо_Хоногийн_Үйл_Ажиллагааны_Тайлан",
        "en_name": "Weekly Operations Report",
        "mn_name": "Долоо хоногийн үйл ажиллагааны тайлан",
    },
    "monthly_pdf": {
        "extension": "pdf",
        "en_stem": "Monthly_KPI_Pack",
        "mn_stem": "Сарын_KPI_Тайлан",
        "en_name": "Monthly KPI Pack",
        "mn_name": "Сарын KPI тайлан",
    },
    "excel_export": {
        "extension": "xlsx",
        "en_stem": "Mine_Manager_AI_Executive_Export",
        "mn_stem": "Уурхайн_Менежер_AI_Удирдлагын_Экспорт",
        "en_name": "Executive Excel Export",
        "mn_name": "Удирдлагын Excel экспорт",
    },
    "board_pack": {
        "extension": "pptx",
        "en_stem": "Mine_Manager_AI_Executive_Board_Pack",
        "mn_stem": "Уурхайн_Менежер_AI_Удирдлагын_Танилцуулга",
        "en_name": "Executive Board Pack",
        "mn_name": "Удирдлагын танилцуулга",
    },
}

_MN_MONTHS = (
    "1-р сар",
    "2-р сар",
    "3-р сар",
    "4-р сар",
    "5-р сар",
    "6-р сар",
    "7-р сар",
    "8-р сар",
    "9-р сар",
    "10-р сар",
    "11-р сар",
    "12-р сар",
)

_UNSAFE_FILENAME_CHARACTERS = re.compile(r'[\\/:*?"<>|\x00-\x1f\x7f]')


def normalize_report_language(value: object = None) -> ReportLanguage:
    """Normalize public report language values to the supported codes."""

    normalized = str(value or "").strip().lower()
    if normalized in _MONGOLIAN_LANGUAGE_VALUES:
        return "mn"
    return "en"


def localize_report_label(key: str, language: object = "en") -> str:
    """Resolve a shared semantic label without changing its logic code."""

    normalized_key = str(key or "").strip().lower().replace("-", " ")
    normalized_key = "_".join(normalized_key.split())
    normalized_language = normalize_report_language(language)
    return _COMMON_LABELS[normalized_language].get(
        normalized_key,
        _COMMON_LABELS["en"].get(normalized_key, str(key or "")),
    )


def get_report_display_name(report_type: str, language: object = "en") -> str:
    """Return a localized display name for a supported report type."""

    definition = _REPORT_DEFINITIONS.get(report_type)
    if definition is None:
        raise ValueError(f"Unsupported report type: {report_type}")
    normalized_language = normalize_report_language(language)
    return definition[f"{normalized_language}_name"]


def localize_mine_display_name(mine_name: object, language: object = "en") -> str:
    """Compatibility shim that preserves the configured/source identity."""

    source_name = str(mine_name or "").strip()
    normalize_report_language(language)
    return source_name


def format_report_date(
    value: date | datetime,
    language: object = "en",
    purpose: DateFormatPurpose = "full_report_date",
) -> str:
    """Format report dates deterministically without relying on OS locales."""

    if not isinstance(value, (date, datetime)):
        raise TypeError("value must be a date or datetime")

    if purpose not in {
        "full_report_date",
        "reporting_period_date",
        "generated_timestamp",
        "short_chart_date",
    }:
        raise ValueError(f"Unsupported date format purpose: {purpose}")

    normalized_language = normalize_report_language(language)
    if normalized_language == "en":
        if purpose == "generated_timestamp":
            return value.strftime("%d %b %Y %H:%M")
        if purpose == "short_chart_date":
            return value.strftime("%d %b")
        return value.strftime("%d %b %Y")

    month_name = _MN_MONTHS[value.month - 1]
    if purpose == "generated_timestamp":
        return f"{value.year} оны {month_name}ын {value.day} {value.strftime('%H:%M')}"
    if purpose == "short_chart_date":
        return f"{month_name}ын {value.day}"
    return f"{value.year} оны {month_name}ын {value.day}"


def pluralize_report_count(
    count: int,
    *,
    language: object = "en",
    singular: str,
    plural: str | None = None,
    mongolian_label: str | None = None,
) -> str:
    """Format a count while keeping Mongolian nouns number-neutral."""

    normalized_language = normalize_report_language(language)
    if normalized_language == "mn":
        return f"{count} {mongolian_label or singular}"
    label = singular if count == 1 else (plural or f"{singular}s")
    return f"{count} {label}"


def build_report_filename(
    report_type: str,
    language: object = "en",
    generated_on: date | datetime | None = None,
) -> str:
    """Build the authoritative dated filename for a report download."""

    definition = _REPORT_DEFINITIONS.get(report_type)
    if definition is None:
        raise ValueError(f"Unsupported report type: {report_type}")

    normalized_language = normalize_report_language(language)
    report_date = generated_on or datetime.now()
    date_suffix = report_date.strftime("%Y-%m-%d")
    stem = definition[f"{normalized_language}_stem"]
    return f"{stem}_{date_suffix}.{definition['extension']}"


def sanitize_report_filename(filename: object) -> str:
    """Remove path separators, control characters, and unsafe filename tokens."""

    sanitized = _UNSAFE_FILENAME_CHARACTERS.sub("_", str(filename or "").strip())
    while ".." in sanitized:
        sanitized = sanitized.replace("..", "_")
    return sanitized.strip(" .") or "report"


def build_content_disposition(
    filename: str,
    ascii_fallback: str | None = None,
) -> str:
    """Build an RFC 5987-compatible attachment header for Unicode filenames."""

    safe_filename = sanitize_report_filename(filename)
    fallback_source = sanitize_report_filename(ascii_fallback or safe_filename)
    fallback = fallback_source.encode("ascii", "ignore").decode("ascii").strip(" .")
    fallback = fallback or "report"
    encoded_filename = quote(safe_filename, safe="")
    return (
        f'attachment; filename="{fallback}"; '
        f"filename*=UTF-8''{encoded_filename}"
    )


@lru_cache(maxsize=1)
def _register_mongolian_pdf_fonts() -> dict[str, str]:
    """Register the pinned DejaVu Sans fonts for Mongolian PDF rendering."""

    from matplotlib import font_manager
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    regular_path = font_manager.findfont(
        font_manager.FontProperties(family="DejaVu Sans", weight="normal"),
        fallback_to_default=False,
    )
    bold_path = font_manager.findfont(
        font_manager.FontProperties(family="DejaVu Sans", weight="bold"),
        fallback_to_default=False,
    )

    regular_name = "MineManagerAI-DejaVuSans"
    bold_name = "MineManagerAI-DejaVuSans-Bold"
    registered = set(pdfmetrics.getRegisteredFontNames())
    if regular_name not in registered:
        pdfmetrics.registerFont(TTFont(regular_name, regular_path))
    if bold_name not in registered:
        pdfmetrics.registerFont(TTFont(bold_name, bold_path))
    pdfmetrics.registerFontFamily(
        regular_name,
        normal=regular_name,
        bold=bold_name,
        italic=regular_name,
        boldItalic=bold_name,
    )

    return {
        "regular": regular_name,
        "bold": bold_name,
        "regular_path": regular_path,
        "bold_path": bold_path,
    }


def ensure_report_pdf_fonts(language: object = "en") -> dict[str, str]:
    """Return language-aware PDF fonts without changing the English baseline."""

    if normalize_report_language(language) == "mn":
        return _register_mongolian_pdf_fonts()
    return {
        "regular": "Helvetica",
        "bold": "Helvetica-Bold",
        "regular_path": "",
        "bold_path": "",
    }
