import React, { useCallback, useEffect, useState } from "react";

import {
  Alert,
  Box,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Tooltip,
  Typography,
} from "@mui/material";

import RefreshIcon from "@mui/icons-material/Refresh";

import { getReportHistory } from "../../api/reportHistoryApi";


function ReportHistoryTable({ refreshKey = 0 }) {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [errorMessage, setErrorMessage] = useState("");


  const loadHistory = useCallback(async () => {
    try {
      setLoading(true);
      setErrorMessage("");

      const response = await getReportHistory();

      const reportHistory = Array.isArray(response)
        ? response
        : response?.items || response?.history || [];

      setHistory(reportHistory);
    } catch (error) {
      console.error("Unable to load report history:", error);

      setErrorMessage(
        "Unable to load report history. Please confirm the backend is running."
      );
    } finally {
      setLoading(false);
    }
  }, []);


  useEffect(() => {
    loadHistory();
  }, [loadHistory, refreshKey]);


  const formatGeneratedDate = (value) => {
    if (!value) {
      return "—";
    }

    const generatedDate = new Date(value);

    if (Number.isNaN(generatedDate.getTime())) {
      return value;
    }

    return generatedDate.toLocaleString([], {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  };


  const formatReportType = (value) => {
    if (!value) {
      return "—";
    }

    return value.toUpperCase();
  };


  const getStatusColor = (status) => {
    const normalizedStatus = status?.toLowerCase();

    if (
      normalizedStatus === "completed" ||
      normalizedStatus === "success"
    ) {
      return "success";
    }

    if (
      normalizedStatus === "failed" ||
      normalizedStatus === "error"
    ) {
      return "error";
    }

    return "warning";
  };


  const getStatusLabel = (status) => {
    const normalizedStatus = status?.toLowerCase();

    if (
      normalizedStatus === "completed" ||
      normalizedStatus === "success"
    ) {
      return "Done";
    }

    if (
      normalizedStatus === "failed" ||
      normalizedStatus === "error"
    ) {
      return "Failed";
    }

    return status || "Unknown";
  };


  return (
    <Card
      sx={{
        mt: 4,
        borderRadius: 3,
        border: "1px solid #e5e7eb",
        boxShadow: "0 8px 24px rgba(15, 23, 42, 0.05)",
        overflow: "hidden",
      }}
    >
      <CardContent
        sx={{
          p: {
            xs: 2,
            sm: 3,
          },
          "&:last-child": {
            pb: {
              xs: 2,
              sm: 3,
            },
          },
        }}
      >
        <Box
          sx={{
            mb: 3,
            display: "flex",
            alignItems: {
              xs: "flex-start",
              sm: "center",
            },
            justifyContent: "space-between",
            gap: 2,
          }}
        >
          <Box>
            <Typography
              variant="h6"
              sx={{
                fontWeight: 800,
                color: "#0f172a",
              }}
            >
              Report History
            </Typography>

            <Typography
              variant="body2"
              sx={{
                mt: 0.5,
                color: "#64748b",
              }}
            >
              Recent executive reports generated by Mine Manager AI.
            </Typography>
          </Box>

          <Tooltip title="Refresh report history">
            <span>
              <IconButton
                onClick={loadHistory}
                disabled={loading}
                sx={{
                  border: "1px solid #e2e8f0",
                  borderRadius: 2,
                  color: "#475569",
                  bgcolor: "#ffffff",
                  "&:hover": {
                    bgcolor: "#f8fafc",
                  },
                }}
              >
                <RefreshIcon />
              </IconButton>
            </span>
          </Tooltip>
        </Box>

        {errorMessage && (
          <Alert
            severity="error"
            sx={{
              mb: 3,
              borderRadius: 2,
            }}
          >
            {errorMessage}
          </Alert>
        )}

        {loading ? (
          <Box
            sx={{
              minHeight: 180,
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              gap: 2,
            }}
          >
            <CircularProgress size={32} />

            <Typography
              variant="body2"
              color="text.secondary"
            >
              Loading report history...
            </Typography>
          </Box>
        ) : history.length === 0 ? (
          <Box
            sx={{
              py: 6,
              textAlign: "center",
              border: "1px dashed #cbd5e1",
              borderRadius: 3,
              bgcolor: "#f8fafc",
            }}
          >
            <Typography
              sx={{
                fontWeight: 700,
                color: "#334155",
              }}
            >
              No report history yet
            </Typography>

            <Typography
              variant="body2"
              sx={{
                mt: 0.75,
                color: "#64748b",
              }}
            >
              Generate a PDF, PowerPoint, or Excel report to create the first
              history record.
            </Typography>
          </Box>
        ) : (
          <TableContainer
            component={Paper}
            elevation={0}
            sx={{
              border: "1px solid #e2e8f0",
              borderRadius: 3,
              overflowX: "auto",
            }}
          >
            <Table
              size="small"
              sx={{
                minWidth: 650,
                tableLayout: "fixed",
              }}
            >
              <TableHead>
                <TableRow
                  sx={{
                    bgcolor: "#f8fafc",
                  }}
                >
                  <TableCell
                    sx={{
                      width: "31%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Report
                  </TableCell>

                  <TableCell
                    sx={{
                      width: "9%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Format
                  </TableCell>

                  <TableCell
                    sx={{
                      width: "13%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Mine
                  </TableCell>

                  <TableCell
                    sx={{
                      width: "21%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Generated
                  </TableCell>

                  <TableCell
                    sx={{
                      width: "9%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Size
                  </TableCell>

                  <TableCell
                    sx={{
                      width: "17%",
                      fontWeight: 800,
                      color: "#334155",
                      fontSize: "0.72rem",
                    }}
                  >
                    Status
                  </TableCell>
                </TableRow>
              </TableHead>

              <TableBody>
                {history.map((report) => (
                  <TableRow
                    key={report.id}
                    hover
                    sx={{
                      "&:last-child td": {
                        borderBottom: 0,
                      },
                    }}
                  >
                    <TableCell>
                      <Box
                        sx={{
                          minWidth: 0,
                        }}
                      >
                        <Tooltip
                          title={report.report_name || ""}
                          placement="top-start"
                        >
                          <Typography
                            variant="body2"
                            sx={{
                              fontSize: "0.75rem",
                              fontWeight: 700,
                              color: "#0f172a",
                              overflow: "hidden",
                              textOverflow: "ellipsis",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {report.report_name || "Unnamed Report"}
                          </Typography>
                        </Tooltip>

                        <Tooltip
                          title={
                            report.filename ||
                            report.report_key ||
                            ""
                          }
                          placement="bottom-start"
                        >
                          <Typography
                            variant="caption"
                            sx={{
                              display: "block",
                              mt: 0.25,
                              fontSize: "0.62rem",
                              color: "#94a3b8",
                              overflow: "hidden",
                              textOverflow: "ellipsis",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {report.filename ||
                              report.report_key ||
                              "—"}
                          </Typography>
                        </Tooltip>
                      </Box>
                    </TableCell>

                    <TableCell>
                      <Chip
                        label={formatReportType(
                          report.report_format
                        )}
                        size="small"
                        variant="outlined"
                        sx={{
                          minWidth: 46,
                          height: 22,
                          fontSize: "0.65rem",
                          fontWeight: 700,
                          borderRadius: 1.5,
                          "& .MuiChip-label": {
                            px: 0.75,
                          },
                        }}
                      />
                    </TableCell>

                    <TableCell>
                      <Tooltip
                        title={report.mine_name || ""}
                      >
                        <Typography
                          variant="body2"
                          sx={{
                            fontSize: "0.72rem",
                            overflow: "hidden",
                            textOverflow: "ellipsis",
                            whiteSpace: "nowrap",
                          }}
                        >
                          {report.mine_name || "—"}
                        </Typography>
                      </Tooltip>
                    </TableCell>

                    <TableCell>
                      <Box
                        sx={{
                          minWidth: 0,
                        }}
                      >
                        <Tooltip
                          title={report.generated_by || ""}
                        >
                          <Typography
                            variant="body2"
                            sx={{
                              fontSize: "0.72rem",
                              fontWeight: 600,
                              color: "#334155",
                              overflow: "hidden",
                              textOverflow: "ellipsis",
                              whiteSpace: "nowrap",
                            }}
                          >
                            {report.generated_by || "System"}
                          </Typography>
                        </Tooltip>

                        <Typography
                          variant="caption"
                          sx={{
                            display: "block",
                            mt: 0.25,
                            fontSize: "0.62rem",
                            color: "#94a3b8",
                            lineHeight: 1.35,
                          }}
                        >
                          {formatGeneratedDate(
                            report.generated_at
                          )}
                        </Typography>
                      </Box>
                    </TableCell>

                    <TableCell>
                      <Typography
                        variant="body2"
                        sx={{
                          fontSize: "0.7rem",
                          whiteSpace: "nowrap",
                        }}
                      >
                        {report.file_size_display || "—"}
                      </Typography>
                    </TableCell>

                    <TableCell>
                      <Chip
                        label={getStatusLabel(report.status)}
                        color={getStatusColor(report.status)}
                        size="small"
                        sx={{
                          minWidth: 52,
                          height: 22,
                          fontSize: "0.68rem",
                          fontWeight: 700,
                          textTransform: "capitalize",
                          "& .MuiChip-label": {
                            px: 1,
                          },
                        }}
                      />
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        )}
      </CardContent>
    </Card>
  );
}


export default ReportHistoryTable;